apiVersion: v1
kind: Pod
metadata:  
  name: nginx
spec:
  containers:
  - name: nginx
    image: quay.io/bitnami/nginx
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 256Mi