apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: cka-workshop
spec:
  portal:
    registration:
      type: anonymous
    updates:
      workshop: true
  workshops:
  - name: cka-workshop
    capacity: 1
    reserved: 1
    expires: 1h
    orphaned: 10m
