apiVersion: v1
kind: Pod
metadata:
  name: nginx-rbac
  namespace: question4
spec:
  # serviceAccountName: q4-sa
  containers:
  - name: nginx-rbac
    image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/nginx

